---
  - name: Update
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt: 
      upgrade: yes

  # - name: Creates directory
  #   become: yes
  #   file:
  #     path: ~/web
  #     state: directory

  - name: Unarchive files
    become: yes
    unarchive:
      src: "files/artifact.tar.gz"
      dest: .

  # - name: Copy index test page
  #   template:
  #     src: "files/*"
  #     dest: "~/web/index.js"

  - name: "Start application"
    become: yes
    shell: |
      cd ~/web
      npm install
      pm2 stop default
      pm2 start npm -- start


# VS Code Extension Version: 1.5.0